"""Check the two run boundaries: `mh.sh begin` reserves and stamps, `mh.sh end` fills and seals.

Original request:
Asked for the run-start and run-end bookkeeping to collapse into one call each, so a run stamps
the record's header, worker pins and repo state, reports what repo memory holds, fingerprints the
files it is about to touch, and at the end fills the agent's five lines, closes `repo state`,
stamps `usage`, writes the memory lines it can derive, and seals the record. Later asked that
begin and end be the only bookkeeping: the request is stamped at begin, every agent line comes in
through an end flag or stays `unknown`, matching routes are printed at begin, friction lands in
memory as an observation, memory lines are never duplicated on a retry, and the usage stamped at
end is provisional and bound to the run's own interval.
"""

from datetime import datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]


def bash_path():
    """Git Bash on Windows; plain `bash` there is a WSL stub that cannot see the fixture paths."""
    if os.name == "nt":
        program_files = Path(os.environ.get("ProgramFiles", "C:/Program Files"))
        for candidate in (program_files / "Git/bin/bash.exe", program_files / "Git/usr/bin/bash.exe"):
            if candidate.exists():
                return str(candidate)
    return shutil.which("bash")


GATE = ("gate     advisors only on a [mini-harness gate] signal line the hook injected this request, "
        "or an on-dial; no signal, no advisor. prompt: version → look it up yourself · research → "
        "online-researcher · alternatives → diversifier. tool drift: 1st → look up the pinned "
        "version yourself · 2nd → online-researcher · 3rd → devils-advocate. Pass what fired, "
        "or \"none fired\", in --advisory at end")


@unittest.skipUnless(bash_path(), "Bash is required")
class BoundaryTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory(prefix="mh-boundary-")
        self.addCleanup(temp.cleanup)
        self.base = Path(temp.name)
        self.repo = self.base / "repo"
        self.h = self.repo / ".harness"
        for directory in ("exec_traj", "repo_info", "state"):
            (self.h / directory).mkdir(parents=True)
        # No adjacent pack: nothing this fixture runs can reach the real repo's definitions.
        self.helper = self.base / "mh.sh"
        self.helper.write_text((ROOT / "skills/mini-harness/mh.sh").read_text(encoding="utf-8"),
                               encoding="utf-8", newline="\n")
        shutil.copyfile(ROOT / "skills/mini-harness/mh_usage.py", self.base / "mh_usage.py")
        shutil.copyfile(ROOT / "harness/exec_traj.md", self.h / "exec_traj.md")
        for name in ("preference.md", "routes.md", "known_issues.md", "persistent_issues.md",
                     "past_QA.md", "update_logs.md", "codebase_overview.md",
                     "scripts_overview.md"):
            (self.h / "repo_info" / name).write_text("", encoding="utf-8", newline="\n")

    def env(self, **extra):
        env = os.environ.copy()
        for key in ("CLAUDECODE", "CLAUDE_PROJECT_DIR", "CLAUDE_PLUGIN_ROOT",
                    "CODEX_HOME", "CODEX_SANDBOX"):
            env.pop(key, None)
        # An empty config dir: this repo has no Claude Code transcripts, so `usage` stays unknown.
        env["CLAUDE_CONFIG_DIR"] = str(self.base / "no-config")
        env.update(extra)
        return env

    def mh(self, *args, success=True, **extra):
        result = subprocess.run([bash_path(), self.helper.as_posix(), *args], cwd=self.repo,
                                capture_output=True, text=True, encoding="utf-8", timeout=120,
                                env=self.env(**extra))
        self.assertEqual(result.returncode == 0, success, result.stdout + result.stderr)
        return result.stdout if success else result.stdout + result.stderr

    def workers(self):
        claude = self.repo / ".claude/agents"
        claude.mkdir(parents=True)
        for role, effort in (("implementer", "medium"), ("verifier", "medium"),
                             ("online-researcher", "high")):
            (claude / f"{role}.md").write_text(
                f'---\nname: {role}\nmodel: "sonnet"\neffort: {effort}\n---\n'
                "Generated by mini-harness sync_agents.py\n", encoding="utf-8", newline="\n")
        codex = self.repo / ".codex/agents"
        codex.mkdir(parents=True)
        (codex / "implementer.toml").write_text(
            'model = "gpt-5.6-sol"\nmodel_reasoning_effort = "medium"\nsandbox_mode = "x"\n'
            'developer_instructions = """\nGenerated by mini-harness sync_agents.py\n"""\n',
            encoding="utf-8", newline="\n")

    def begin(self, *args, **extra):
        output = self.mh("begin", *args, **extra)
        name = next(line.split(None, 1)[1].strip() for line in output.splitlines()
                    if line.startswith("record "))
        return output, Path(name).name

    def read(self, name):
        return (self.h / "exec_traj" / name).read_text(encoding="utf-8")

    def line(self, name, key):
        for text in self.read(name).splitlines():
            if text.startswith(key + ":"):
                return text
        self.fail(f"no {key!r} line in {name}:\n{self.read(name)}")

    # ---------------------------------------------------------------- begin
    def test_begin_reserves_the_record_and_stamps_header_workers_and_repo_state(self):
        self.workers()
        output, name = self.begin("update", CLAUDECODE="1")
        self.assertTrue(output.startswith("record "), output)
        self.assertRegex(self.read(name), r"# update · \d{4}-\d\d-\d\d \d\d:\d\d · claude-code · <main model>")
        self.assertEqual(self.line(name, "workers"),
                         "workers: claude sonnet/medium except online-researcher sonnet/high"
                         " · codex gpt-5.6-sol/medium")
        state = self.line(name, "repo state")
        self.assertIn("dirty files", state)
        self.assertIn("pending trajectories", state)
        self.assertNotIn(" → ", state, "the closing half belongs to `end`")
        self.assertIn("1 pending", self.mh("status"))

    def test_begin_reads_the_platform_from_the_environment_and_survives_missing_definitions(self):
        _, name = self.begin("query", CODEX_HOME="/somewhere")
        self.assertIn("· codex · <main model>", self.read(name))
        self.assertEqual(self.line(name, "workers"), "workers: none found")
        _, plain = self.begin("query")
        self.assertIn("· <platform> · <main model>", self.read(plain))

    def test_begin_reports_what_repo_memory_holds_with_preference_inline(self):
        (self.h / "repo_info/preference.md").write_text(
            "no emoji in output\nask before installing\n", encoding="utf-8", newline="\n")
        (self.h / "repo_info/known_issues.md").write_text("a\nb\nc\n", encoding="utf-8", newline="\n")
        output, _ = self.begin("update")
        memory = next(text for text in output.splitlines() if text.startswith("memory "))
        self.assertIn(".harness/repo_info/ (README.md indexes it)", memory)
        self.assertIn("preference.md: no emoji in output; ask before installing", memory)
        self.assertIn("known_issues 3 lines", memory)
        self.assertIn("persistent_issues 0", memory)
        self.assertIn("past_QA 0", memory)
        self.assertIn("update_logs 0", memory)
        self.assertIn("overviews empty", memory)
        (self.h / "repo_info/codebase_overview.md").write_text("x\n", encoding="utf-8", newline="\n")
        (self.h / "repo_info/preference.md").write_text("", encoding="utf-8", newline="\n")
        output, _ = self.begin("update")
        self.assertIn("overviews present", output)
        self.assertIn("preference.md: empty", output)

    def test_begin_fingerprints_each_named_file_including_a_missing_one(self):
        (self.repo / "source with spaces.txt").write_text("first\n", encoding="utf-8")
        output, _ = self.begin("update", "source with spaces.txt", "gone.txt")
        prints = [text for text in output.splitlines() if text.startswith("fingerprint ")]
        self.assertEqual(2, len(prints), output)
        self.assertRegex(prints[0], r"^fingerprint [0-9a-f]{64}  source with spaces\.txt$")
        self.assertEqual("fingerprint missing  gone.txt", prints[1])
        # a path that escapes the repo is refused before anything is reserved
        before = sorted(p.name for p in (self.h / "exec_traj").iterdir())
        self.mh("begin", "update", "../outside", success=False)
        self.assertEqual(before, sorted(p.name for p in (self.h / "exec_traj").iterdir()))

    def test_begin_prints_the_gate_rule_verbatim(self):
        output, _ = self.begin("update")
        self.assertIn(GATE, output)

    # ---------------------------------------------------------------- end
    def test_end_fills_the_five_lines_closes_repo_state_and_stamps_usage(self):
        _, name = self.begin("update")
        # values carrying the separators that bit a sed-based implementation
        output = self.mh("end", name,
                         "--outcome", "achieved — one call per boundary",
                         "--dispositions", 'diversifier/D1 · adopt-part "awk & env" · sonnet/medium',
                         "--changed", "files mh.sh, hooks/route.sh · tests added",
                         "--effect", "helped exec_traj — begin|end removed 6 calls",
                         "--friction", "stamping — sed / delimiter → awk")
        self.assertIn("sealed   " + name, output)
        self.assertEqual(self.line(name, "outcome"), "outcome: achieved — one call per boundary")
        self.assertEqual(self.line(name, "dispositions"),
                         'dispositions: diversifier/D1 · adopt-part "awk & env" · sonnet/medium')
        self.assertEqual(self.line(name, "changed"),
                         "changed: files mh.sh, hooks/route.sh · tests added")
        self.assertEqual(self.line(name, "harness effect"),
                         "harness effect: helped exec_traj — begin|end removed 6 calls")
        self.assertEqual(self.line(name, "friction"), "friction: stamping — sed / delimiter → awk")
        state = self.line(name, "repo state")
        self.assertIn(" → ", state)
        self.assertRegex(state, r" → .*dirty files · head .* at \d\d:\d\d$")
        self.assertEqual(self.line(name, "usage"), "usage: unknown — no transcript found")

    def test_end_stamps_usage_from_the_newest_transcript_when_one_exists(self):
        config = self.base / "with-config"
        project = config / "projects" / re.sub(r"[^A-Za-z0-9]", "-", str(self.repo))
        project.mkdir(parents=True)
        now = datetime.now(timezone.utc)
        stamp = lambda delta: (now + delta).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        turn = {"type": "assistant", "timestamp": stamp(timedelta(seconds=-30)),
                "message": {"id": "msg_a", "role": "assistant",
                            "content": [{"type": "tool_use", "id": "t0", "name": "Read",
                                         "input": {}}],
                            "usage": {"input_tokens": 10, "output_tokens": 5,
                                      "cache_read_input_tokens": 0,
                                      "cache_creation_input_tokens": 0}}}
        # an earlier turn from a previous run: not this record's, so never counted
        earlier = dict(turn, timestamp=stamp(timedelta(hours=-2)),
                       message=dict(turn["message"], id="msg_old"))
        prompt = {"type": "user", "timestamp": stamp(timedelta(minutes=-1)),
                  "message": {"role": "user", "content": "the request"}}
        last = dict(turn, timestamp=stamp(timedelta(minutes=6)))
        (project / "11111111-2222-3333-4444-555555555555.jsonl").write_text(
            "\n".join(json.dumps(r) for r in (earlier, prompt, turn, last)) + "\n",
            encoding="utf-8", newline="\n")
        _, name = self.begin("update", CLAUDE_CONFIG_DIR=str(config))
        self.mh("end", name, CLAUDE_CONFIG_DIR=str(config))
        self.assertEqual(self.line(name, "usage"),
                         "usage: provisional · 7m00s · 1 model calls · 1 tool calls · 15 tokens"
                         " · session 11111111")

    def test_end_never_overwrites_a_line_the_agent_wrote_by_hand(self):
        _, name = self.begin("update")
        path = self.h / "exec_traj" / name
        path.write_text(path.read_text(encoding="utf-8").replace(
            "outcome: achieved | partial | not achieved — <≤ 12 words>",
            "outcome: partial — written during the run"), encoding="utf-8", newline="\n")
        self.mh("end", name, "--outcome", "achieved — stamped at the end",
                "--friction", "none")
        self.assertEqual(self.line(name, "outcome"), "outcome: partial — written during the run")
        self.assertEqual(self.line(name, "friction"), "friction: none")

    def test_end_writes_friction_to_persistent_issues_but_never_a_none(self):
        _, first = self.begin("update")
        self.mh("end", first, "--friction", "none")
        self.assertEqual("", (self.h / "repo_info/persistent_issues.md").read_text(encoding="utf-8"))
        _, second = self.begin("debug")
        output = self.mh("end", second, "--friction", "sealing — receipt path guessed → pass the basename")
        issues = (self.h / "repo_info/persistent_issues.md").read_text(encoding="utf-8")
        self.assertRegex(issues, r"^- \d{4}-\d\d-\d\d · debug · observed · scope \S+ \S+ · sealing — "
                                 r"receipt path guessed → pass the basename — evidence: exec_traj/"
                                 + re.escape(second) + r" · fix: proposed$")
        self.assertIn("persistent_issues.md", output)
        # the same friction from another run is one lesson, not two
        _, third = self.begin("debug")
        self.mh("end", third, "--friction", "sealing — receipt path guessed → pass the basename")
        text = (self.h / "repo_info/persistent_issues.md").read_text(encoding="utf-8")
        self.assertEqual(2, text.count("\n"), "one line per run, the evidence differs")
        self.assertIn("noted", self.mh("note", "persistent_issues.md", "- same line"))
        self.assertIn("noted", self.mh("note", "persistent_issues.md", "- same line"))
        self.assertEqual(1, (self.h / "repo_info/persistent_issues.md")
                         .read_text(encoding="utf-8").count("- same line"))

    def test_end_prepends_update_logs_for_a_change_tag_and_not_for_a_query(self):
        _, name = self.begin("update", "--request", "collapse the run bookkeeping into begin and end")
        self.assertEqual(self.line(name, "request"),
                         "request: collapse the run bookkeeping into begin and end")
        self.mh("end", name, "--changed", "files mh.sh · tests added")
        logs = (self.h / "repo_info/update_logs.md").read_text(encoding="utf-8")
        self.assertRegex(logs, r"^- \d{4}-\d\d-\d\d · update · collapse the run bookkeeping into"
                               r" begin and end · files mh.sh · tests added\n")
        _, query = self.begin("query")
        self.mh("end", query, "--changed", "files none · tests none")
        self.assertEqual(1, (self.h / "repo_info/update_logs.md")
                         .read_text(encoding="utf-8").count("\n"), "a query never logs an update")

    def test_end_seals_the_record_and_refuses_it_once_it_has_changed(self):
        _, name = self.begin("update")
        self.mh("end", name, "--outcome", "achieved — sealed")
        self.assertIn("batch     " + name, self.mh("wiki", "begin"))
        self.assertIn("already sealed", self.mh("end", name))
        path = self.h / "exec_traj" / name
        with path.open("a", encoding="utf-8", newline="\n") as handle:
            handle.write("edited after sealing\n")
        self.assertIn("completed record changed", self.mh("end", name, success=False))

    def test_end_refuses_a_path_or_a_missing_record(self):
        for bad in ("sub/dir.md", "../escape.md", "never-written.md", "record.txt"):
            result = subprocess.run([bash_path(), self.helper.as_posix(), "end", bad],
                                    cwd=self.repo, capture_output=True, text=True,
                                    encoding="utf-8", timeout=60, env=self.env())
            self.assertEqual(2, result.returncode, bad + ": " + result.stdout + result.stderr)


    # ---------------------------------------------------------------- the only bookkeeping
    def test_end_takes_every_agent_line_as_a_flag_and_leaves_unknown_where_none_was_passed(self):
        _, name = self.begin("update")
        self.mh("end", name, "--request", "late request", "--native-path", "direct · 2 edits",
                "--memory", "none", "--advisory", "researcher direct lookup docs.example",
                "--verification", "pytest → exit 0 — 3 passed", "--choices", "none",
                "--outcome", "achieved — done")
        text = self.read(name)
        self.assertNotIn("<!-- fill from", text, "the fill hint is bookkeeping, not record content")
        self.assertEqual(self.line(name, "request"), "request: late request")
        self.assertEqual(self.line(name, "native path"), "native path: direct · 2 edits")
        self.assertEqual(self.line(name, "memory consulted"), "memory consulted: none")
        self.assertEqual(self.line(name, "advisory"), "advisory: researcher direct lookup docs.example")
        self.assertEqual(self.line(name, "verification"), "verification: pytest → exit 0 — 3 passed")
        self.assertEqual(self.line(name, "user choices"), "user choices: none")
        for key in ("dispositions", "changed", "harness effect", "friction"):
            self.assertEqual(self.line(name, key), key + ": unknown")
        self.assertNotIn("<", "".join(l for l in text.splitlines()[1:] if not l.startswith("#")),
                         "no placeholder survives sealing:\n" + text)
        self.assertEqual("", (self.h / "repo_info/update_logs.md").read_text(encoding="utf-8"),
                         "an unknown change never logs an update")
        self.assertEqual("", (self.h / "repo_info/persistent_issues.md").read_text(encoding="utf-8"),
                         "unknown friction is not a lesson")

    def test_begin_prints_the_routes_matching_the_request_words_and_the_named_files(self):
        (self.h / "repo_info/routes.md").write_text(
            "- worker settings, effort, subagent model → entry mh.sh edit_worker → consumers agents/ → tests tests/test_mh_effort.py → verify py -m pytest tests/test_mh_effort.py\n"
            "- token usage, cost report → entry mh_usage.py → consumers mh.sh end → tests tests/test_mh_usage.py → verify py -m pytest tests/test_mh_usage.py\n"
            "- lock owner, wiki batch → entry mh.sh wiki → consumers hooks/consolidate.sh → tests tests/test_mh_lifecycle.py → verify py -m pytest\n",
            encoding="utf-8", newline="\n")
        (self.repo / "mh_usage.py").write_text("x\n", encoding="utf-8")
        output, _ = self.begin("update", "--request", "change the effort control for workers")
        routes = [l for l in output.splitlines() if l.startswith("route ")]
        self.assertEqual(1, len(routes), output)
        self.assertIn("worker settings, effort", routes[0])
        output, _ = self.begin("debug", "--request", "why is it slow", "mh_usage.py")
        routes = [l for l in output.splitlines() if l.startswith("route ")]
        self.assertEqual(1, len(routes), output)
        self.assertIn("token usage", routes[0])
        output, _ = self.begin("query", "--request", "what does the pipeline do")
        self.assertNotIn("route ", output, "no matching words, no route")
        # on-demand lookup, and the empty-file case
        self.assertIn("lock owner", self.mh("routes", "wiki"))
        self.assertIn("no match", self.mh("routes", "zzzz"))
        (self.h / "repo_info/routes.md").write_text("", encoding="utf-8")
        self.assertIn("routes.md is empty", self.mh("routes", "wiki"))
        self.assertIn("noted", self.mh("note", "routes.md", "- a → entry b → consumers c → tests d → verify e"))

    def test_begin_refuses_a_request_flag_without_a_value(self):
        self.mh("begin", "update", "--request", success=False)
        self.assertEqual([], list((self.h / "exec_traj").iterdir()))


if __name__ == "__main__":
    unittest.main()
