"""Exercise trajectory completion, wiki ownership, and init restoration.

Original request:
Fixed the lifecycle and concurrency defects found in the trajectory-driven patch,
including research boundaries and restoration after an init session restart.
"""

from concurrent.futures import ThreadPoolExecutor
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import time
import unittest


ROOT = Path(__file__).resolve().parents[1]


def bash_path():
    if os.name == "nt":
        candidate = Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Git/bin/bash.exe"
        if candidate.exists():
            return str(candidate)
    return shutil.which("bash")


@unittest.skipUnless(bash_path(), "Bash is required")
class LifecycleTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory(prefix="mh-lifecycle-")
        self.addCleanup(temp.cleanup)
        self.base = Path(temp.name)
        self.repo = self.base / "repo"
        self.h = self.repo / ".harness"
        for directory in ("exec_traj", "repo_info", "state"):
            (self.h / directory).mkdir(parents=True)
        # No adjacent pack: mutations can only reach this disposable repo's workers.
        self.helper = self.base / "mh.sh"
        self.helper.write_text((ROOT / "skills/mini-harness/mh.sh").read_text(encoding="utf-8"),
                               encoding="utf-8", newline="\n")
        shutil.copyfile(ROOT / "harness/exec_traj.md", self.h / "exec_traj.md")
        self.lock = self.h / "state/wiki_lock"

    def mh(self, *args, success=True):
        result = subprocess.run([bash_path(), self.helper.as_posix(), *args], cwd=self.repo,
                                capture_output=True, text=True, encoding="utf-8", timeout=60)
        self.assertEqual(result.returncode == 0, success, result.stdout + result.stderr)
        return result.stdout

    def record(self, number, complete=False):
        name = f"2026-01-01_0000{number:02d}_update_0001.md"
        path = self.h / "exec_traj" / name
        path.write_text("# update | Codex | test\noutcome: partial\nharness effect: pending\n",
                        encoding="utf-8", newline="\n")
        if complete:
            self.mh("traj", "complete", name)
        return path

    def owner(self, output, prefix="owner"):
        return next(line.split()[1] for line in output.splitlines() if line.startswith(prefix + " "))

    def cursor(self, name):
        (self.h / "repo_info/harness_effect.md").write_text(
            f"consolidated through {name}\n", encoding="utf-8", newline="\n")

    def workers(self):
        directory = self.repo / ".claude/agents"
        directory.mkdir(parents=True)
        for role in ("implementer", "online-researcher"):
            (directory / f"{role}.md").write_text(
                f'---\nname: {role}\nmodel: "sonnet"\neffort: medium\n---\n'
                'Generated by mini-harness sync_agents.py\n', encoding="utf-8", newline="\n")
        return directory

    def test_start_registers_run_and_header_edits_never_complete_it(self):
        name = self.mh("traj", "update").strip().rsplit("/", 1)[-1]
        path = self.h / "exec_traj" / name
        self.assertIn("repo state:", path.read_text(encoding="utf-8"))
        self.assertIn("1 pending", self.mh("status"))
        path.write_text("# update | Codex | test\noutcome: <fill later>\n", encoding="utf-8")
        old = time.time() - 172800
        os.utime(path, (old, old))
        self.assertIn("batch     none", self.mh("wiki", "begin"))
        self.assertFalse(self.lock.exists())
        self.assertIn("1 pending", self.mh("status"))

    def test_seal_requires_unchanged_content_and_is_idempotent(self):
        path = self.record(1, complete=True)
        self.mh("traj", "complete", path.name)
        output = self.mh("wiki", "begin")
        self.assertIn("batch     " + path.name, output)
        self.mh("wiki", "end", self.owner(output))
        path.write_text("changed after completion\n", encoding="utf-8")
        self.mh("traj", "complete", path.name, success=False)
        self.assertIn("batch     none", self.mh("wiki", "begin"))
        self.assertFalse(self.lock.exists())

    def test_empty_and_blocked_batches_never_hold_lock(self):
        for _ in range(2):
            self.assertIn("batch     none", self.mh("wiki", "begin"))
            self.assertFalse(self.lock.exists())
        self.record(1)
        self.record(2, complete=True)
        self.assertIn("batch     none", self.mh("wiki", "begin"))
        self.assertFalse(self.lock.exists())

    def test_already_consolidated_legacy_records_are_not_live_sessions(self):
        path = self.record(1)
        self.cursor(path.name)
        self.assertIn("0 pending", self.mh("status"))
        self.assertIn("batch     none", self.mh("wiki", "begin"))

    def test_old_lock_never_expires_and_wrong_owner_cannot_release(self):
        self.record(1, complete=True)
        owner = self.owner(self.mh("wiki", "begin"))
        os.utime(self.lock, (time.time() - 7200,) * 2)
        self.mh("wiki", "begin", success=False)
        self.mh("wiki", "end", "wrong-owner", success=False)
        self.assertEqual(owner, self.lock.read_text().strip())
        self.mh("wiki", "end", owner)
        replacement = self.owner(self.mh("wiki", "begin"))
        self.assertNotEqual(owner, replacement)
        self.mh("wiki", "end", owner, success=False)
        self.assertEqual(replacement, self.lock.read_text().strip())
        self.mh("wiki", "end", replacement)

    def test_batches_stop_before_pending_and_drain_without_leaking(self):
        paths = [self.record(i, complete=(i != 3)) for i in range(1, 9)]
        first = self.mh("wiki", "begin")
        self.assertEqual(2, first.count("batch     "))
        self.cursor(paths[1].name)
        self.mh("wiki", "end", self.owner(first))
        self.assertIn("batch     none", self.mh("wiki", "begin"))
        self.assertFalse(self.lock.exists())
        self.mh("traj", "complete", paths[2].name)
        second = self.mh("wiki", "begin")
        self.assertEqual(5, second.count("batch     "))
        self.cursor(paths[6].name)
        self.mh("wiki", "end", self.owner(second))
        third = self.mh("wiki", "begin")
        self.assertEqual(1, third.count("batch     "))
        self.cursor(paths[7].name)
        self.mh("wiki", "end", self.owner(third))
        self.assertIn("batch     none", self.mh("wiki", "begin"))
        self.assertFalse(self.lock.exists())

    def test_concurrent_acquisition_has_only_one_owner(self):
        self.record(1, complete=True)
        def begin():
            return subprocess.run([bash_path(), self.helper.as_posix(), "wiki", "begin"],
                                  cwd=self.repo, capture_output=True, text=True, timeout=60)
        with ThreadPoolExecutor(max_workers=2) as pool:
            results = list(pool.map(lambda _: begin(), range(2)))
        self.assertEqual([0, 1], sorted(r.returncode for r in results))
        output = next(r.stdout for r in results if r.returncode == 0)
        self.mh("wiki", "end", self.owner(output))
        self.assertFalse((self.h / "state/wiki_guard").exists())

    def test_fingerprints_detect_dirty_file_edits_creation_and_deletion(self):
        path = self.repo / "source with spaces.txt"
        path.write_text("first\n", encoding="utf-8")
        before = self.mh("fingerprint", path.name, "new.txt")
        path.write_text("second\n", encoding="utf-8")
        after = self.mh("fingerprint", path.name, "new.txt")
        self.assertNotEqual(before, after)
        self.assertIn("missing  new.txt", after)
        (self.repo / "new.txt").write_text("new\n", encoding="utf-8")
        self.assertNotEqual(after, self.mh("fingerprint", path.name, "new.txt"))
        path.unlink()
        self.assertIn("missing  " + path.name, self.mh("fingerprint", path.name))
        self.mh("fingerprint", "../outside", success=False)

    def test_init_restores_across_processes_without_touching_regular_snapshot(self):
        directory = self.workers()
        self.mh("effort", "save")
        regular = self.h / "state/effort_saved"
        original = regular.read_bytes()
        before = {p.name: p.read_bytes() for p in directory.iterdir()}
        owner = self.owner(self.mh("effort", "init-save"), "init-owner")
        self.mh("effort", "max", "claude-model=opus")
        self.assertIn(owner, self.mh("status"))  # a fresh process sees the pending owner
        self.mh("effort", "init-save", success=False)
        self.mh("effort", "init-restore", "unrelated", success=False)
        self.assertIn("effort: max", (directory / "implementer.md").read_text())
        self.mh("effort", "init-restore", owner)
        self.assertEqual(before, {p.name: p.read_bytes() for p in directory.iterdir()})
        self.assertEqual(original, regular.read_bytes())
        self.assertFalse((self.h / "state/init_effort_saved").exists())
        self.assertNotIn("pending restoration", self.mh("status"))

    def test_init_keep_consumes_only_its_own_snapshot(self):
        directory = self.workers()
        owner = self.owner(self.mh("effort", "init-save"), "init-owner")
        self.mh("effort", "high")
        self.mh("effort", "init-keep", "unrelated", success=False)
        self.mh("effort", "init-keep", owner)
        self.assertIn("effort: high", (directory / "implementer.md").read_text())
        self.assertFalse((self.h / "state/init_effort_saved").exists())

    def test_model_only_change_preserves_each_workers_effort(self):
        directory = self.workers()
        researcher = directory / "online-researcher.md"
        researcher.write_text(researcher.read_text().replace("effort: medium", "effort: high"),
                              encoding="utf-8", newline="\n")
        self.mh("effort", "keep", "claude-model=opus")
        self.assertIn('model: "opus"', (directory / "implementer.md").read_text())
        self.assertIn("effort: medium", (directory / "implementer.md").read_text())
        self.assertIn("effort: high", researcher.read_text())

    def test_rewrite_warning_precedes_reported_mutation(self):
        self.workers()
        self.record(1)
        output = self.mh("effort", "high")
        self.assertLess(output.index("warn"), output.index("rewrote"))
        self.assertIn("pending trajectory", output)


if __name__ == "__main__":
    unittest.main()
