#!/usr/bin/env bash
# Workspace helper: activation, traj <task>|complete <file>, wiki begin|end <owner>, fingerprint <files>, effort, subagents.
#
# Original request: activation must bootstrap the writable workspace layout even
# for a plugin-only install, and on/off/status/hooks must agree on one root rule.
#
# Root rule (shared with hooks/route.sh): walking up from the cwd, the first
# directory that contains `.harness/` or `.git` is the workspace root; else the cwd.
# Resources: `<root>/.harness/` (writable: protocol copy, repo_info/, exec_traj/,
# state/). When it is missing, `on` bootstraps it from the pack next to this
# skill (`<pack>/harness/`, present in a plugin or pack checkout).
set -u
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PACK=""; [ -f "$SKILL_DIR/../../harness/harness.md" ] && PACK="$(cd "$SKILL_DIR/../.." && pwd -P)"
PROTO_FILES="harness.md tasks.md exec_traj.md worker_models.md philosophy.md repo_map.md reinitialize.md loop_control.md stay_active.md"
MEMORY_FILES="preference.md known_issues.md persistent_issues.md update_logs.md past_QA.md codebase_overview.md scripts_overview.md harness_effect.md"
MARKER="Generated by mini-harness sync_agents.py"   # only generated worker definitions are ever rewritten

find_root() { local d=$1; while :; do
  if [ -d "$d/.harness" ] || [ -e "$d/.git" ]; then printf '%s' "$d"; return 0; fi
  [ "$d" = / ] && return 1; d=$(dirname "$d"); done; }
ROOT=$(find_root "$PWD") || ROOT=$PWD
H="$ROOT/.harness"
hash_of() { local digest
  if command -v sha256sum >/dev/null 2>&1; then digest=$(sha256sum "$1") || return 1
  else digest=$(shasum -a 256 "$1") || return 1; fi
  printf '%s\n' "${digest%% *}"; }

ensure_layout() {
  if [ ! -f "$H/harness.md" ]; then
    [ -n "$PACK" ] || { echo "mini-harness: no .harness/ under $ROOT and no pack resources next to this skill — run: bash <pack>/install.sh \"$ROOT\"" >&2; return 1; }
    mkdir -p "$H"
    for f in $PROTO_FILES; do cp "$PACK/harness/$f" "$H/$f"; printf '%s\t%s\n' "$(hash_of "$H/$f")" ".harness/$f" >> "$H/installed.tsv"; done
    echo "bootstrapped $H from $PACK/harness (protocol files)"
  fi
  mkdir -p "$H/repo_info" "$H/exec_traj" "$H/state"
  if [ ! -f "$H/repo_info/README.md" ]; then
    src="$PACK/harness/repo_info_README.md"; [ -f "$src" ] || src="$H/repo_info_README.md"
    [ -f "$src" ] && cp "$src" "$H/repo_info/README.md"
  fi
  for f in $MEMORY_FILES; do [ -f "$H/repo_info/$f" ] || : > "$H/repo_info/$f"; done
}
style_path() {
  for c in "$SKILL_DIR/../i-have-adhd/SKILL.md" "$ROOT/.agents/skills/i-have-adhd/SKILL.md" "$ROOT/.claude/skills/i-have-adhd/SKILL.md"; do
    [ -f "$c" ] && { (cd "$(dirname "$c")" && printf '%s/SKILL.md' "$(pwd -P)"); return; }; done
  printf 'skill i-have-adhd'
}
wiki_cursor() { sed -n 's/.*consolidated through \([^[:space:]]*\).*/\1/p' "$H/repo_info/harness_effect.md" 2>/dev/null | tail -n1; }
traj_count() { ls "$H/exec_traj" 2>/dev/null | grep -c '\.md$' || true; }
# Completion receipts seal the content, independent of header text or age. Legacy records need explicit completion too.
in_flight() { local receipt="$H/state/trajectories/${1##*/}.sha256" digest
  [ -s "$receipt" ] && digest=$(hash_of "$1") && [ "$(cat "$receipt")" = "$digest" ] && return 1; return 0; }
in_flight_count() { local n=0 f c; c=$(wiki_cursor)
  for f in "$H"/exec_traj/*.md; do [ -f "$f" ] || continue; [ "${f##*/}" \> "$c" ] || continue; in_flight "$f" && n=$((n+1)); done; printf '%s' "$n"; }
unconsolidated() { local c n=0 f; c=$(wiki_cursor)
  for f in "$H"/exec_traj/*.md; do [ -f "$f" ] || continue; [ "${f##*/}" \> "$c" ] || continue; in_flight "$f" && continue; n=$((n+1)); done; printf '%s' "$n"; }
# Advisory only: definitions are shared, and running sessions may retain their loaded copies.
live_warn() { local k; k=$(in_flight_count); [ "$k" -gt 0 ] && echo "warn     $k pending trajectory record(s) — sessions may be running; about to rewrite shared definitions (loaded sessions may not reload)"; return 0; }
# Serialize short state transitions. No age-based takeover: recover a guard only after its process is known to be gone.
state_guard() { mkdir -p "$H/state" || return 1; G="$H/state/$1_guard"
  mkdir "$G" 2>/dev/null || { echo "mh.sh: state operation busy ($G); recover only after its process has stopped" >&2; return 1; }
  trap 'rmdir "$G" 2>/dev/null' EXIT; trap 'exit 130' INT; trap 'exit 143' TERM HUP; }
owner_token() { printf '%s-%s-%s-%s' "$(date +%s)" "$$" "$RANDOM" "$RANDOM"; }
# Effort control: rewrite model/effort in a generated definition in place ("" = keep; "inherit" = drop the effort line / model pin).
edit_claude() { local f=$1 m=$2 e=$3 t; t=$(mktemp)
  awk -v m="$m" -v e="$e" 'BEGIN{fm=0}
    /^---$/ && fm<2 { fm++; if(fm==2){ if(m!="" && !sm) print "model: \"" m "\""; if(e!="" && e!="inherit" && !se) print "effort: " e }; print; next }
    fm==1 && /^model:/ { sm=1; if(m!=""){ print "model: \"" m "\""; next } }
    fm==1 && /^effort:/ { se=1; if(e!=""){ if(e!="inherit") print "effort: " e; next } }
    { print }' "$f" > "$t" && cat "$t" > "$f"; local rc=$?; rm -f "$t"; return "$rc"; }
edit_codex() { local f=$1 m=$2 e=$3 t hm he; t=$(mktemp)
  hm=$(awk '/^developer_instructions = /{exit} /^model = /{n++} END{print n+0}' "$f")
  he=$(awk '/^developer_instructions = /{exit} /^model_reasoning_effort = /{n++} END{print n+0}' "$f")
  awk -v m="$m" -v e="$e" -v hm="$hm" -v he="$he" '
    /^developer_instructions = / { body=1 }
    body { print; next }
    /^model = / { if(m!=""){ if(m!="inherit") print "model = \"" m "\""; next } }
    /^model_reasoning_effort = / { if(e!=""){ if(e!="inherit") print "model_reasoning_effort = \"" e "\""; next } }
    { print }
    /^sandbox_mode = / { if(m!="" && m!="inherit" && hm==0) print "model = \"" m "\""; if(e!="" && e!="inherit" && he==0) print "model_reasoning_effort = \"" e "\"" }' "$f" > "$t" && cat "$t" > "$f"; local rc=$?; rm -f "$t"; return "$rc"; }
# Worker definition dirs: the repo's own, else the plugin's agents/ for Claude Code; Codex only in the repo.
worker_dirs() { cdir=""; ls "$ROOT/.claude/agents"/*.md >/dev/null 2>&1 && cdir="$ROOT/.claude/agents"
  [ "${1:-}" != local ] && [ -z "$cdir" ] && [ -n "$PACK" ] && ls "$PACK/agents"/*.md >/dev/null 2>&1 && cdir="$PACK/agents"   # legacy effort command: the plugin's own agents/
  xdir=""; ls "$ROOT/.codex/agents"/*.toml >/dev/null 2>&1 && xdir="$ROOT/.codex/agents"
  if [ "${1:-}" = local ]; then
    # A repo toggle must not rewrite a shared plugin (including an external directory symlink).
    local real_root real_dir; real_root=$(cd "$ROOT" && pwd -P)
    if [ -n "$cdir" ]; then real_dir=$(cd "$cdir" && pwd -P); case "$real_dir" in "$real_root"/*) ;; *) cdir="";; esac; fi
    if [ -n "$xdir" ]; then real_dir=$(cd "$xdir" && pwd -P); case "$real_dir" in "$real_root"/*) ;; *) xdir="";; esac; fi
  fi
  [ -n "$cdir$xdir" ] || { echo "mh.sh effort: no worker definitions under $ROOT/.claude/agents, $ROOT/.codex/agents, or the pack — run install.sh or /mini-harness on" >&2; return 1; }; }
# Effective values as written in a definition; a missing line means inherit.
claude_val() { local v; v=$(awk '/^---$/{fm++; next} fm==1{print}' "$1" | sed -n "s/^$2: *\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p" | head -n1); printf '%s' "${v:-inherit}"; }
codex_val() { local v; v=$(awk '/^developer_instructions = /{exit} {print}' "$1" | sed -n "s/^$2 = \"\([^\"]*\)\"$/\1/p" | head -n1); printf '%s' "${v:-inherit}"; }
print_effective() { [ -n "$1" ] && [ -f "$1/implementer.md" ] && echo "effective claude · $(grep -E '^(model|effort):' "$1/implementer.md" | tr '\n' ' ')· researcher $(grep -E '^effort:' "$1/online-researcher.md" 2>/dev/null | tr '\n' ' ')"
  [ -n "$2" ] && [ -f "$2/implementer.toml" ] && echo "effective codex · $(grep -E '^(model|model_reasoning_effort) = ' "$2/implementer.toml" | tr '\n' ' ')· researcher $(grep -E '^model_reasoning_effort = ' "$2/online-researcher.toml" 2>/dev/null | tr '\n' ' ')"; return 0; }
# Rewrite every generated definition: $1/$2 = Claude model/effort, $3/$4 = Codex model/effort, $5/$6 = researcher efforts (Claude, Codex).
apply_settings() { local cm=$1 lvl=$2 xm=$3 xlvl=$4 rlvl=$5 xrlvl=$6 f e; nc=0; nx=0
  for f in ${cdir:+"$cdir"/*.md}; do [ -f "$f" ] && [ ! -L "$f" ] && grep -q "$MARKER" "$f" || continue
    e=$lvl; [ "$(basename "$f" .md)" = online-researcher ] && e=$rlvl
    edit_worker claude "$f" "$cm" "$e" || return 1; nc=$((nc+1)); done
  for f in ${xdir:+"$xdir"/*.toml}; do [ -f "$f" ] && [ ! -L "$f" ] && grep -q "$MARKER" "$f" || continue
    e=$xlvl; [ "$(basename "$f" .toml)" = online-researcher ] && e=$xrlvl
    edit_worker codex "$f" "$xm" "$e" || return 1; nx=$((nx+1)); done; }
refresh_manifest() { local r=$1 h; [ -f "$H/installed.tsv" ] && grep -q "	$r\$" "$H/installed.tsv" || return 0   # keep the rewritten file "owned and unmodified"
  h=$(hash_of "$ROOT/$r"); awk -F'\t' -v OFS='\t' -v p="$r" -v h="$h" '$2==p{$1=h}1' "$H/installed.tsv" > "$H/installed.tsv.tmp" && mv "$H/installed.tsv.tmp" "$H/installed.tsv"; }
edit_worker() { local platform=$1 f=$2 rel recorded="" owned=false; rel=${f#"$ROOT"/}
  [ -f "$H/installed.tsv" ] && recorded=$(awk -F'\t' -v p="$rel" '$2==p{print $1; exit}' "$H/installed.tsv")
  [ -n "$recorded" ] && [ "$recorded" = "$(hash_of "$f")" ] && owned=true
  "edit_$platform" "$f" "$3" "$4" || return 1
  # Never mark pre-existing user edits as installer-owned just because a setting changed.
  if $owned; then refresh_manifest "$rel" || return 1; fi; return 0; }
# Snapshot the definitions' current settings to $1 (an existing snapshot is kept: returns 1) / put $1 back and remove it (none: returns 1).
snap_val() { sed -n "s/^$2=//p" "$1" | head -n1; }
save_settings() { local f; [ -f "$1" ] && return 1; mkdir -p "$H/state" || return 1
  { echo "saved=$(date '+%Y-%m-%d %H:%M')"
    [ -n "$cdir" ] && [ -f "$cdir/implementer.md" ] && { echo "claude_model=$(claude_val "$cdir/implementer.md" model)"; echo "claude_effort=$(claude_val "$cdir/implementer.md" effort)"; echo "claude_researcher=$(claude_val "$cdir/online-researcher.md" effort)"; }
    [ -n "$xdir" ] && [ -f "$xdir/implementer.toml" ] && { echo "codex_model=$(codex_val "$xdir/implementer.toml" model)"; echo "codex_effort=$(codex_val "$xdir/implementer.toml" model_reasoning_effort)"; echo "codex_researcher=$(codex_val "$xdir/online-researcher.toml" model_reasoning_effort)"; }
    # Keep every worker's own settings; the implementer is not a template for the other roles.
    echo "format=2"
    for f in ${cdir:+"$cdir"/*.md}; do [ -f "$f" ] && [ ! -L "$f" ] && grep -q "$MARKER" "$f" || continue
      printf 'claude\t%s\t%s\t%s\n' "${f##*/}" "$(claude_val "$f" model)" "$(claude_val "$f" effort)"; done
    for f in ${xdir:+"$xdir"/*.toml}; do [ -f "$f" ] && [ ! -L "$f" ] && grep -q "$MARKER" "$f" || continue
      printf 'codex\t%s\t%s\t%s\n' "${f##*/}" "$(codex_val "$f" model)" "$(codex_val "$f" model_reasoning_effort)"; done
  } > "$1" || return 1; return 0; }
restore_settings() { [ -f "$1" ] || return 1
  if [ "$(snap_val "$1" format)" = 2 ]; then
    local platform f m e; nc=0; nx=0
    while IFS=$'\t' read -r platform f m e; do
      case "$platform" in claude|codex) ;; *) continue;; esac
      # Bind by role filename, not the shell's spelling of the repo path (e.g. /var vs /private/var).
      case "$platform" in
        claude) [ -n "$cdir" ] || continue; f="$cdir/${f##*/}";;
        codex) [ -n "$xdir" ] || continue; f="$xdir/${f##*/}";;
      esac
      [ -f "$f" ] && [ ! -L "$f" ] && grep -q "$MARKER" "$f" || continue
      case "$platform:$f" in
        claude:"$cdir"/*.md) edit_worker claude "$f" "$m" "$e" || return 1; nc=$((nc+1));;
        codex:"$xdir"/*.toml) edit_worker codex "$f" "$m" "$e" || return 1; nx=$((nx+1));;
        *) continue;;
      esac
    done < "$1"
  else
    apply_settings "$(snap_val "$1" claude_model)" "$(snap_val "$1" claude_effort)" "$(snap_val "$1" codex_model)" "$(snap_val "$1" codex_effort)" "$(snap_val "$1" claude_researcher)" "$(snap_val "$1" codex_researcher)" || return 1
  fi
  rm -f "$1"; }
sub_line() { [ -f "$H/state/subagents" ] && echo "subagents on · since $(snap_val "$H/state/subagents" since) · $(grep -v '^since=' "$H/state/subagents" | tr '_\n' '- ' | sed 's/ $//')" || echo "subagents off (default) — every subagent runs as the platform decides"; }
# Argument checks shared by `effort` and `subagents` ($1 = command name for the message).
check_levels() { local c=$1 l; shift; for l in "$@"; do case "$l" in ""|low|medium|high|xhigh|max|inherit) ;; *) echo "mh.sh $c: unknown level '$l' (low|medium|high|xhigh|max|inherit)" >&2; return 1;; esac; done; }
check_models() { case "$2" in gpt-*) echo "mh.sh $1: '$2' is a Codex model — use codex-model=" >&2; return 1;; *[!A-Za-z0-9._:/-]*) echo "mh.sh $1: bad model id '$2'" >&2; return 1;; esac
  case "$3" in claude-*|opus|sonnet|haiku|fable) echo "mh.sh $1: '$3' is a Claude model — use claude-model=" >&2; return 1;; *[!A-Za-z0-9._:/-]*) echo "mh.sh $1: bad model id '$3'" >&2; return 1;; esac; }

cmd=${1:-status}
case "$cmd" in
  on)
    ensure_layout || exit 1
    date '+%Y-%m-%d %H:%M' > "$H/state/active"
    echo "mini-harness on · root $ROOT · protocol $H/harness.md · style $(style_path)";;
  off)
    rm -f "$H/state/active"; echo "mini-harness off · root $ROOT";;
  status|doctor)
    fail=0; ok() { echo "ok    $*"; }; warn() { echo "warn  $*"; }; bad() { echo "FAIL  $*"; fail=1; }
    echo "root      $ROOT"
    if [ -f "$H/state/active" ]; then echo "active    yes · since $(head -n1 "$H/state/active")"; else echo "active    no"; fi
    if [ -f "$H/harness.md" ]; then ok "protocol $H/harness.md"; else bad "no $H/harness.md — run: on (plugin) or install.sh (standalone)"; fi
    if [ -s "$H/repo_info/codebase_overview.md" ]; then ok "repo_info initialized (codebase_overview.md non-empty)"; else warn "repo_info not initialized — run: init"; fi
    cur=$(wiki_cursor); echo "traj      $(traj_count) trajectories · $(unconsolidated) unconsolidated · $(in_flight_count) pending (wiki cursor: ${cur:-none}; consolidate with: wiki)"
    ca=$(ls "$ROOT/.claude/agents" 2>/dev/null | grep -c '\.md$' || true); cx=$(ls "$ROOT/.codex/agents" 2>/dev/null | grep -c '\.toml$' || true)
    echo "workers   .claude/agents: $ca · .codex/agents: $cx (0 = expect the plugin's agents on Claude Code; Codex needs install.sh)"
    cdef="$ROOT/.claude/agents"; [ -f "$cdef/implementer.md" ] || cdef="${PACK:+$PACK/agents}"   # plugin install: the plugin's own agents/
    if [ -n "$cdef" ] && [ -f "$cdef/implementer.md" ]; then echo "effective claude · $(grep -E '^(model|effort):' "$cdef/implementer.md" | tr '\n' ' ')· researcher $(grep -E '^effort:' "$cdef/online-researcher.md" 2>/dev/null | tr '\n' ' ')($cdef; change with: effort; read at session start)"; fi
    if [ -f "$ROOT/.codex/agents/implementer.toml" ]; then echo "effective codex · $(grep -E '^(model|model_reasoning_effort) = ' "$ROOT/.codex/agents/implementer.toml" | tr '\n' ' ')· researcher $(grep -E '^model_reasoning_effort = ' "$ROOT/.codex/agents/online-researcher.toml" 2>/dev/null | tr '\n' ' ')(.codex/agents)"; fi
    sub_line
    [ -f "$H/state/init_effort_saved" ] && echo "init      pending restoration · owner $(snap_val "$H/state/init_effort_saved" owner) (resume init; effort init-restore <owner>)"
    [ "$cmd" = status ] && exit 0
    for f in $PROTO_FILES; do [ -f "$H/$f" ] || bad "missing $H/$f"; done
    [ -f "$H/hooks/route.sh" ] && { [ -x "$H/hooks/route.sh" ] && ok "standalone route hook executable" || bad "$H/hooks/route.sh is not executable"; }
    if [ -f "$ROOT/.claude/settings.json" ] && grep -q 'route.sh' "$ROOT/.claude/settings.json"; then
      grep -q '\\"${CLAUDE_PROJECT_DIR}/.harness/hooks/route.sh\\"' "$ROOT/.claude/settings.json" && ok "Claude hook path is quoted" || bad "Claude hook path unquoted — re-run install.sh (F3)"
      grep -q 'Agent|Task' "$ROOT/.claude/settings.json" && ok "Claude Agent hook wired (subagents control)" || warn "no Agent hook in .claude/settings.json — re-run install.sh so 'subagents on' reaches the platform's own subagents"
    else warn "no standalone Claude hook in .claude/settings.json (fine for a plugin install)"; fi
    if [ -f "$ROOT/.codex/hooks.json" ] && grep -q 'route.sh' "$ROOT/.codex/hooks.json"; then
      grep -q 'dirname' "$ROOT/.codex/hooks.json" && ok "Codex hook resolves the root itself (trust it once with /hooks)" || bad "Codex hook uses a cwd-relative path — re-run install.sh (F3)"
    else warn "no standalone Codex hook in .codex/hooks.json (fine for a plugin install)"; fi
    if [ -f "$ROOT/AGENTS.md" ] && grep -q 'mini-harness:begin' "$ROOT/AGENTS.md"; then ok "AGENTS.md carries the block"; else warn "no AGENTS.md block (plugin install: the hook reminder covers routing)"; fi
    if [ -f "$H/installed.tsv" ]; then
      while IFS=$'\t' read -r h p; do
        [ "$h" = link ] && { [ -L "$ROOT/$p" ] || warn "owned link missing: $p"; continue; }
        [ -f "$ROOT/$p" ] || { warn "owned file missing: $p"; continue; }
        [ "$(hash_of "$ROOT/$p")" = "$h" ] || warn "owned file modified locally (install.sh will keep it): $p"
      done < "$H/installed.tsv"
      ok "ownership manifest checked ($(wc -l < "$H/installed.tsv" | tr -d ' ') entries)"
    else warn "no ownership manifest ($H/installed.tsv)"; fi
    [ -f "$H/state/active" ] && [ ! -f "$H/harness.md" ] && bad "active marker without protocol files"
    # An unpinned worker inherits the main model: 46 of the first 49 advisor spawns ran on Fable / Opus that way.
    unp=""; for f in ${cdef:+"$cdef"/*.md}; do [ -f "$f" ] && grep -q "$MARKER" "$f" && [ "$(claude_val "$f" model)" = inherit ] && unp="$unp ${f##*/}"; done
    for f in "$ROOT"/.codex/agents/*.toml; do [ -f "$f" ] && grep -q "$MARKER" "$f" && [ "$(codex_val "$f" model)" = inherit ] && unp="$unp ${f##*/}"; done
    [ -n "$unp" ] && warn "worker definitions without a model pin (they inherit the main model):$unp — intended only on an explicit inherit; otherwise: effort <level> claude-model=<alias> codex-model=<id>"
    exit $fail;;
  note)
    # note <memory file> "<line>" | note untaken "<line>" — add one line to repo memory without the agent reading the file
    # first (each read lands in the main context for the rest of the session). update_logs.md is newest-first, so it
    # is prepended; the others are appended; `untaken` lands under `## Untaken options` in known_issues.md.
    f=${2:?usage: mh.sh note <preference.md|known_issues.md|persistent_issues.md|update_logs.md|past_QA.md|untaken> "<line>"}; shift 2; line="$*"
    [ -n "$line" ] || { echo "mh.sh note: empty line" >&2; exit 2; }; mkdir -p "$H/repo_info"
    case "$f" in
      update_logs.md) p="$H/repo_info/$f"; [ -f "$p" ] || : > "$p"; t=$(mktemp); { printf '%s\n' "$line"; cat "$p"; } > "$t" && cat "$t" > "$p"; rm -f "$t";;
      preference.md|known_issues.md|persistent_issues.md|past_QA.md) p="$H/repo_info/$f"; printf '%s\n' "$line" >> "$p";;
      untaken) p="$H/repo_info/known_issues.md"; [ -f "$p" ] || : > "$p"
        if grep -q '^## Untaken options' "$p"; then t=$(mktemp)
          awk -v l="$line" 'BEGIN{s=0;b=""} /^## Untaken options/{s=1; print; next}
            s==1 && /^$/ {b=b"\n"; next}                       # hold the section'"'"'s trailing blank lines
            s==1 && /^## /{print l; printf "%s", b; s=2; b=""}  # new line goes last in the section, blanks after it
            s==1 {printf "%s", b; b=""} {print} END{if(s==1) print l}' "$p" > "$t" && cat "$t" > "$p"; rm -f "$t"
        else printf '\n## Untaken options\n%s\n' "$line" >> "$p"; fi;;
      *) echo "mh.sh note: unknown target '$f'" >&2; exit 2;;
    esac; echo "noted → $p"; exit 0;;
  untaken)
    # untaken [n] — the last n parked options (default 5), for the diversifier's `history:` line
    n=${2:-5}; p="$H/repo_info/known_issues.md"; [ -f "$p" ] || exit 0
    awk 'BEGIN{s=0} /^## Untaken options/{s=1; next} s==1 && /^## /{s=0} s==1 && NF{print}' "$p" | tail -n "$n"; exit 0;;
  effort)
    # effort <low|medium|high|xhigh|max|inherit|reset|save|restore> [researcher=<level>] [claude-model=<id|inherit>] [codex-model=<id|inherit>] [model=<id|inherit>]
    # The one effort/model control that works the same on both platforms: both read a worker's effort from its
    # definition (the Claude Code Agent tool takes model aliases only and has no effort parameter; a Codex agent
    # file's settings win over a spawn request). Rewrites only generated definitions; `reset` = shipped defaults.
    # `save` snapshots the current settings to state/effort_saved (kept if one exists); `restore` puts that snapshot
    # back and removes it. Init uses an independent owner-tagged snapshot across its restart.
    lvl=${2:-}; [ -n "$lvl" ] || { echo "usage: mh.sh effort <level|keep|reset|save|restore|init-save|init-restore <owner>|init-keep <owner>> [researcher=<level>] [claude-model=<id|inherit>] [codex-model=<id|inherit>]" >&2; exit 2; }
    shift 2; rlvl=""; cm=""; xm=""; SAVED="$H/state/effort_saved"
    case "$lvl" in
      init-save|init-restore|init-keep)
        state_guard init_effort || exit 1; SAVED="$H/state/init_effort_saved"
        if [ "$lvl" = init-save ]; then
          [ $# -eq 0 ] || { echo "usage: effort init-save" >&2; exit 2; }
          [ ! -e "$SAVED" ] || { echo "mh.sh: pending init snapshot; resume owner $(snap_val "$SAVED" owner) before starting another" >&2; exit 1; }
          worker_dirs || exit 1; token=$(owner_token)
          save_settings "$SAVED" || exit 1
          printf 'owner=%s\n' "$token" >> "$SAVED" || exit 1
          echo "init-owner $token"; echo "init snapshot saved; retain owner across restart"; exit 0
        fi
        [ $# -eq 1 ] && [ -n "$1" ] && [ -f "$SAVED" ] && [ "$(snap_val "$SAVED" owner)" = "$1" ] || { echo "mh.sh: init snapshot owner mismatch or missing snapshot" >&2; exit 1; }
        if [ "$lvl" = init-keep ]; then rm "$SAVED" || exit 1; echo "init snapshot cleared; current settings retained"; exit 0; fi
        worker_dirs || exit 1; live_warn
        restore_settings "$SAVED" || exit 1
        echo "init settings restored"; print_effective "$cdir" "$xdir"; exit 0;;
    esac
    case "$lvl" in save|restore) [ $# -eq 0 ] || { echo "mh.sh effort $lvl takes no arguments" >&2; exit 2; };; esac
    worker_dirs || exit 1
    if [ "$lvl" = save ]; then
      save_settings "$SAVED" || { echo "mini-harness effort · snapshot kept ($SAVED, $(snap_val "$SAVED" saved)) — restore it before saving another"; exit 0; }
      echo "mini-harness effort · saved current settings to $SAVED (restore with: effort restore)"; print_effective "$cdir" "$xdir"; exit 0
    fi
    if [ "$lvl" = restore ]; then
      when=$(snap_val "$SAVED" saved 2>/dev/null)
      [ -f "$SAVED" ] || { echo "mini-harness effort · no snapshot ($SAVED) — definitions unchanged"; print_effective "$cdir" "$xdir"; exit 0; }
      live_warn; restore_settings "$SAVED" || exit 1
      echo "mini-harness effort · restored the settings saved $when · rewrote $nc Claude Code definition(s)${cdir:+ in $cdir} · $nx Codex definition(s)${xdir:+ in $xdir}"
      print_effective "$cdir" "$xdir"; echo "note: a running session may not reload definitions — check each worker's launch metadata and record requested vs effective"; exit 0
    fi
    [ "$lvl" = reset ] && { lvl=medium; rlvl=high; cm=sonnet; xm=gpt-5.6-sol; }   # the shipped defaults (sync_agents.py)
    [ "$lvl" = keep ] && lvl=""   # model-only requests preserve each role's own effort
    for a in "$@"; do case "$a" in
      researcher=*) rlvl=${a#*=};; claude-model=*) cm=${a#*=};; codex-model=*) xm=${a#*=};; model=*) cm=${a#*=}; xm=${a#*=};;
      *) echo "mh.sh effort: unknown argument '$a'" >&2; exit 2;; esac; done
    check_levels effort "$lvl" "$rlvl" && check_models effort "$cm" "$xm" || exit 2
    live_warn
    apply_settings "$cm" "$lvl" "$xm" "$lvl" "$rlvl" "$rlvl" || exit 1
    echo "mini-harness effort · rewrote $nc Claude Code definition(s)${cdir:+ in $cdir} · $nx Codex definition(s)${xdir:+ in $xdir}"
    print_effective "$cdir" "$xdir"
    echo "note: a running session may not reload definitions — check each worker's launch metadata and record requested vs effective"
    exit 0;;
  wiki)
    # No expiry: the owner holds the lock across tool calls, then releases it by token after writing the cursor.
    sub=${2:-begin}; L="$H/state/wiki_lock"
    case "$sub" in
      begin)
        [ $# -le 2 ] || { echo "usage: mh.sh wiki begin" >&2; exit 2; }
        state_guard wiki || exit 1
        [ ! -e "$L" ] || { echo "mini-harness wiki: another consolidation holds $L; no automatic expiry; recover only after its owner has stopped" >&2; exit 1; }
        # Select under the short guard; acquire the long-lived lock only for a nonempty batch.
        c=$(wiki_cursor); n=0; batch=()
        for f in "$H"/exec_traj/*.md; do [ -f "$f" ] || continue; [ "${f##*/}" \> "$c" ] || continue
          if in_flight "$f"; then echo "stop      ${f##*/} is pending — complete or recover it before advancing the cursor"; break; fi
          batch+=("${f##*/}"); n=$((n+1)); [ "$n" -ge 5 ] && break; done
        [ "$n" -gt 0 ] || { echo "batch     none — no lock held"; exit 0; }
        token=$(owner_token)
        ( set -C; printf '%s\n' "$token" > "$L" ) || exit 1
        echo "owner     $token"; echo "wiki      lock taken; release on success or failure with: wiki end $token"
        printf 'batch     %s\n' "${batch[@]}"; exit 0;;
      end)
        [ $# -eq 3 ] && [ -n "$3" ] || { echo "usage: mh.sh wiki end <owner>" >&2; exit 2; }
        state_guard wiki || exit 1
        [ -f "$L" ] && [ "$(cat "$L")" = "$3" ] || { echo "mh.sh wiki: owner mismatch or missing lock; nothing released" >&2; exit 1; }
        rm "$L" || exit 1; echo "wiki      lock released"; exit 0;;
      *) echo "usage: mh.sh wiki begin | end <owner>" >&2; exit 2;;
    esac;;
  subagents)
    # subagents [status] | on [model=<id>] [claude-model=<id>] [codex-model=<id>] [effort=<level>] [researcher=<level>] | off
    # The standing subagent control: off by default, independent of on/off, and it touches nothing but subagent model
    # and effort. `on` writes state/subagents — hooks/route.sh reads it: on Claude Code it fills in the Agent tool's
    # `model` for a spawn that names none, on Codex it reminds the main agent of the spawn arguments — and puts the
    # settings into the generated worker definitions (the only native effort control on Claude Code; on Codex a
    # definition wins over spawn arguments). `off` removes the file and puts back the definitions as they were before `on`.
    sub=${2:-status}; shift; [ $# -gt 0 ] && shift
    S="$H/state/subagents"; SS="$H/state/subagents_saved"
    case "$sub" in
      status) [ $# -eq 0 ] || { echo "mh.sh subagents status takes no arguments" >&2; exit 2; }; sub_line; exit 0;;
      off) [ $# -eq 0 ] || { echo "mh.sh subagents off takes no arguments" >&2; exit 2; }
        worker_dirs local 2>/dev/null || { cdir=""; xdir=""; }
        if [ -f "$SS" ]; then
          live_warn
          restore_settings "$SS" || exit 1
          echo "mini-harness subagents off · worker definitions put back as they were ($nc Claude Code · $nx Codex)"
        else echo "mini-harness subagents off"; fi
        rm -f "$S" || exit 1
        print_effective "$cdir" "$xdir"; echo "note: restored definitions take effect in a new session; running subagents keep their settings"; exit 0;;
      on) ;;
      *) echo "usage: mh.sh subagents [status] | on [model=<id>] [claude-model=<id>] [codex-model=<id>] [effort=<low|medium|high|xhigh|max|inherit>] [researcher=<level>] | off" >&2; exit 2;;
    esac
    cm=""; xm=""; lvl=""; rlvl=""
    for a in "$@"; do
      case "$a" in *=) echo "mh.sh subagents: empty value in '$a'" >&2; exit 2;; esac
      case "$a" in
      claude-model=*) cm=${a#*=};; codex-model=*) xm=${a#*=};; effort=*) lvl=${a#*=};; researcher=*) rlvl=${a#*=};;
      model=*) v=${a#*=}; case "$v" in claude-*|opus|sonnet|haiku|fable) cm=$v;; gpt-*) xm=$v;; *) cm=$v; xm=$v;; esac;;   # a platform's own id goes to that platform only
      *) echo "mh.sh subagents: unknown argument '$a'" >&2; exit 2;; esac; done
    [ -n "$cm$xm$lvl$rlvl" ] || { echo "mh.sh subagents on: name at least one of model= · claude-model= · codex-model= · effort= · researcher=" >&2; exit 2; }
    check_levels subagents "$lvl" "$rlvl" && check_models subagents "$cm" "$xm" || exit 2
    rlvl=${rlvl:-$lvl}   # one effort for every worker unless the researcher gets its own
    worker_dirs local 2>/dev/null || { cdir=""; xdir=""; }   # the hook still serves native subagents without repo definitions
    live_warn
    if [ -f "$SS" ]; then restore_settings "$SS" >/dev/null || exit 1; fi   # repeated `on` starts from the user's own settings
    save_settings "$SS" || exit 1
    apply_settings "$cm" "$lvl" "$xm" "$lvl" "$rlvl" "$rlvl" || exit 1
    { echo "since=$(date '+%Y-%m-%d %H:%M')"; [ -n "$cm" ] && echo "claude_model=$cm"; [ -n "$xm" ] && echo "codex_model=$xm"
      [ -n "$lvl" ] && echo "effort=$lvl"; [ -n "$rlvl" ] && echo "researcher=$rlvl"; :; } > "$S.tmp" && mv "$S.tmp" "$S" || exit 1
    echo "mini-harness $(sub_line) · rewrote $nc Claude Code · $nx Codex worker definition(s)"
    print_effective "$cdir" "$xdir"
    case "$cm" in ""|inherit) ;;
      opus|sonnet|haiku|fable) { grep -q 'Agent|Task' "$ROOT/.claude/settings.json" 2>/dev/null || grep -q 'Agent|Task' "${PACK:-/nonexistent}/hooks/hooks.json" 2>/dev/null; } \
        && echo "claude   every Agent spawn that names no model gets '$cm' from now on (PreToolUse hook; an explicit model on a spawn still wins)" \
        || echo "warn     no Agent hook in $ROOT/.claude/settings.json — re-run install.sh (or use the plugin) so the platform's own subagents get '$cm'";;
      *) echo "claude   '$cm' is a full id: it reaches the mini-harness workers through their definitions; the Agent tool's per-spawn model takes aliases only (opus|sonnet|haiku|fable), so the platform's own subagents keep their model";; esac
    [ -n "$lvl$rlvl" ] && echo "claude   effort reaches repo-installed workers from the next session; built-in subagents keep their session effort (no per-spawn effort control)"
    [ -z "$cdir" ] && [ -n "$cm$lvl$rlvl" ] && echo "note     no repo-local Claude definitions: shared plugin definitions were left alone; install.sh adds local workers for effort/full-ID control"
    [ -n "$xm$lvl$rlvl" ] && echo "codex    the prompt hook requests model / reasoning_effort for new spawns; repo worker definitions carry the same values from the next session"
    echo "note     requested levels must be supported by the selected model; verify launch metadata for effective settings"
    echo "note     nothing else changes; off again with: subagents off"
    exit 0;;
  traj)
    task=${2:?usage: mh.sh traj <task> | complete <filename>}; mkdir -p "$H/exec_traj"
    if [ "$task" = complete ]; then
      name=${3:-}
      case "$name" in ''|*/*|*\\*|.*) echo "mh.sh traj complete: pass a trajectory basename" >&2; exit 2;; esac
      [ $# -eq 3 ] && [ -f "$H/exec_traj/$name" ] && [ ! -L "$H/exec_traj/$name" ] || { echo "mh.sh traj complete: record missing or invalid" >&2; exit 2; }
      case "$name" in *.md) ;; *) echo "mh.sh traj complete: expected .md record" >&2; exit 2;; esac
      mkdir -p "$H/state/trajectories" || exit 1
      receipt="$H/state/trajectories/$name.sha256"; digest=$(hash_of "$H/exec_traj/$name") || exit 1
      [ -n "$digest" ] || exit 1
      if [ -f "$receipt" ]; then
        [ "$(cat "$receipt")" = "$digest" ] || { echo "mh.sh traj: completed record changed; preserve it and record a correction in a new trajectory" >&2; exit 1; }
      else
        ( set -C; printf '%s\n' "$digest" > "$receipt" ) || exit 1
      fi
      echo "completed $name (sealed; do not edit)"; exit 0
    fi
    case "$task" in update|debug|refactor|query|check|exec|pr|init|loop) ;; *) echo "mh.sh traj: unknown task '$task'" >&2; exit 2;; esac
    [ $# -eq 2 ] || exit 2
    # Repo state at run start — the shared-repo line (harness.md §4): what other sessions left, before this run touches anything.
    dirty=$(git -C "$ROOT" status --short 2>/dev/null | wc -l | tr -d ' '); head=$(git -C "$ROOT" log -1 --format='%h %ci' 2>/dev/null | cut -c1-24)
    rs="repo state: ${dirty:-?} dirty files · head ${head:-none} · $(in_flight_count) pending trajectories (stamped $(date '+%H:%M'))"
    for _ in 1 2 3 4 5; do
      f="$H/exec_traj/$(date '+%Y-%m-%d_%H%M%S')_${task}_$(printf '%04x' $((RANDOM % 65536))).md"
      if ( set -C; : > "$f" ) 2>/dev/null; then
        # Write the schema skeleton so the agent fills blanks instead of reading exec_traj.md.
        { printf '<!-- fill from what the run already holds — effect, not narration; keep `unknown` where unresolved; delete this line -->\n'
          if [ -f "$H/exec_traj.md" ]; then sed -n '/^```md$/,/^```$/p' "$H/exec_traj.md" | sed '1d;$d'
          else printf '# <task> · <YYYY-MM-DD HH:MM> · <platform> · <main model>\nrequest:\noutcome:\nnative path:\nrepo state:\nmemory consulted:\nsubagents:\nadvisory:\nadvisor decisions (main agent):\nchanged:\nverification:\nuser choices:\nharness effect:\n- helped:\n- hurt:\n- neutral:\nfriction:\n'; fi
        } | sed "1,2s/^# <task> · <YYYY-MM-DD HH:MM>/# $task · $(date '+%Y-%m-%d %H:%M')/" | sed "s|^repo state:.*|$rs|" > "$f"
        printf '%s\n' "$f"; exit 0
      fi
    done; echo "mini-harness: could not create a unique trajectory file" >&2; exit 1;;
  fingerprint)
    shift; [ $# -gt 0 ] || { echo "usage: mh.sh fingerprint <repo-relative file> ..." >&2; exit 2; }
    for p in "$@"; do
      case "$p" in ''|/*|*\\*|..|../*|*/../*|*/..|*:*) echo "mh.sh fingerprint: expected repo-relative file: $p" >&2; exit 2;; esac
      if [ -f "$ROOT/$p" ]; then digest=$(hash_of "$ROOT/$p") || exit 1; printf '%s  %s\n' "$digest" "$p"
      elif [ -e "$ROOT/$p" ] || [ -L "$ROOT/$p" ]; then echo "mh.sh fingerprint: not a readable regular file: $p" >&2; exit 2
      else printf 'missing  %s\n' "$p"; fi
    done; exit 0;;
  *) echo "usage: mh.sh on | off | status | doctor | traj <task> | traj complete <filename> | note <file|untaken> \"<line>\" | untaken [n] | fingerprint <files...> | wiki begin | wiki end <owner> | effort <level|keep|reset|save|restore|init-save|init-restore <owner>|init-keep <owner>> [researcher=<level>] [claude-model=<id>] [codex-model=<id>] | subagents [status|on ...|off]" >&2; exit 2;;
esac
