#!/usr/bin/env bash
# mini-harness workspace helper — on | off | status | doctor | traj <task> | effort <level|save|restore|reset> …
#
# Original request: activation must bootstrap the writable workspace layout even
# for a plugin-only install, and on/off/status/hooks must agree on one root rule.
#
# Root rule (shared with hooks/route.sh): walking up from the cwd, the first
# directory that contains `.harness/` or `.git` is the workspace root; else the cwd.
# Resources: `<root>/.harness/` (writable: protocol copy, repo_info/, exec_traj/,
# state/). When it is missing, `on` bootstraps it from the pack next to this
# skill (`<pack>/harness/`, present in a plugin or pack checkout).
set -u
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PACK=""; [ -f "$SKILL_DIR/../../harness/harness.md" ] && PACK="$(cd "$SKILL_DIR/../.." && pwd -P)"
PROTO_FILES="harness.md tasks.md exec_traj.md worker_models.md philosophy.md repo_map.md reinitialize.md loop_control.md stay_active.md"
MEMORY_FILES="preference.md known_issues.md persistent_issues.md update_logs.md past_QA.md codebase_overview.md scripts_overview.md harness_effect.md"
MARKER="Generated by mini-harness sync_agents.py"   # only generated worker definitions are ever rewritten

find_root() { local d=$1; while :; do
  if [ -d "$d/.harness" ] || [ -e "$d/.git" ]; then printf '%s' "$d"; return 0; fi
  [ "$d" = / ] && return 1; d=$(dirname "$d"); done; }
ROOT=$(find_root "$PWD") || ROOT=$PWD
H="$ROOT/.harness"
hash_of() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi; }

ensure_layout() {
  if [ ! -f "$H/harness.md" ]; then
    [ -n "$PACK" ] || { echo "mini-harness: no .harness/ under $ROOT and no pack resources next to this skill — run: bash <pack>/install.sh \"$ROOT\"" >&2; return 1; }
    mkdir -p "$H"
    for f in $PROTO_FILES; do cp "$PACK/harness/$f" "$H/$f"; printf '%s\t%s\n' "$(hash_of "$H/$f")" ".harness/$f" >> "$H/installed.tsv"; done
    echo "bootstrapped $H from $PACK/harness (protocol files)"
  fi
  mkdir -p "$H/repo_info" "$H/exec_traj" "$H/state"
  if [ ! -f "$H/repo_info/README.md" ]; then
    src="$PACK/harness/repo_info_README.md"; [ -f "$src" ] || src="$H/repo_info_README.md"
    [ -f "$src" ] && cp "$src" "$H/repo_info/README.md"
  fi
  for f in $MEMORY_FILES; do [ -f "$H/repo_info/$f" ] || : > "$H/repo_info/$f"; done
}
style_path() {
  for c in "$SKILL_DIR/../i-have-adhd/SKILL.md" "$ROOT/.agents/skills/i-have-adhd/SKILL.md" "$ROOT/.claude/skills/i-have-adhd/SKILL.md"; do
    [ -f "$c" ] && { (cd "$(dirname "$c")" && printf '%s/SKILL.md' "$(pwd -P)"); return; }; done
  printf 'skill i-have-adhd'
}
wiki_cursor() { sed -n 's/.*consolidated through \([^[:space:]]*\).*/\1/p' "$H/repo_info/harness_effect.md" 2>/dev/null | tail -n1; }
traj_count() { ls "$H/exec_traj" 2>/dev/null | grep -c '\.md$' || true; }
unconsolidated() { local c; c=$(wiki_cursor); ls "$H/exec_traj" 2>/dev/null | grep '\.md$' | awk -v c="$c" '$0 > c' | wc -l | tr -d ' '; }
# Effort control: rewrite model/effort in a generated definition in place ("" = keep; "inherit" = drop the effort line / model pin).
edit_claude() { local f=$1 m=$2 e=$3 t; t=$(mktemp)
  awk -v m="$m" -v e="$e" 'BEGIN{fm=0}
    /^---$/ && fm<2 { fm++; if(fm==2){ if(m!="" && !sm) print "model: \"" m "\""; if(e!="" && e!="inherit" && !se) print "effort: " e }; print; next }
    fm==1 && /^model:/ { sm=1; if(m!=""){ print "model: \"" m "\""; next } }
    fm==1 && /^effort:/ { se=1; if(e!=""){ if(e!="inherit") print "effort: " e; next } }
    { print }' "$f" > "$t" && cat "$t" > "$f"; rm -f "$t"; }
edit_codex() { local f=$1 m=$2 e=$3 t hm he; t=$(mktemp)
  hm=$(grep -c '^model = ' "$f"); he=$(grep -c '^model_reasoning_effort = ' "$f")
  awk -v m="$m" -v e="$e" -v hm="$hm" -v he="$he" '
    /^model = / { if(m!=""){ if(m!="inherit") print "model = \"" m "\""; next } }
    /^model_reasoning_effort = / { if(e!=""){ if(e!="inherit") print "model_reasoning_effort = \"" e "\""; next } }
    { print }
    /^sandbox_mode = / { if(m!="" && m!="inherit" && hm==0) print "model = \"" m "\""; if(e!="" && e!="inherit" && he==0) print "model_reasoning_effort = \"" e "\"" }' "$f" > "$t" && cat "$t" > "$f"; rm -f "$t"; }
# Worker definition dirs: the repo's own, else the plugin's agents/ for Claude Code; Codex only in the repo.
worker_dirs() { cdir=""; ls "$ROOT/.claude/agents"/*.md >/dev/null 2>&1 && cdir="$ROOT/.claude/agents"
  [ -z "$cdir" ] && [ -n "$PACK" ] && ls "$PACK/agents"/*.md >/dev/null 2>&1 && cdir="$PACK/agents"   # plugin install: the plugin's own agents/
  xdir=""; ls "$ROOT/.codex/agents"/*.toml >/dev/null 2>&1 && xdir="$ROOT/.codex/agents"
  [ -n "$cdir$xdir" ] || { echo "mh.sh effort: no worker definitions under $ROOT/.claude/agents, $ROOT/.codex/agents, or the pack — run install.sh or /mini-harness on" >&2; return 1; }; }
# Effective values as written in a definition; a missing line means inherit.
claude_val() { local v; v=$(sed -n "s/^$2: *\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p" "$1" | head -n1); printf '%s' "${v:-inherit}"; }
codex_val() { local v; v=$(sed -n "s/^$2 = \"\([^\"]*\)\"$/\1/p" "$1" | head -n1); printf '%s' "${v:-inherit}"; }
print_effective() { [ -n "$1" ] && [ -f "$1/implementer.md" ] && echo "effective claude · $(grep -E '^(model|effort):' "$1/implementer.md" | tr '\n' ' ')· researcher $(grep -E '^effort:' "$1/online-researcher.md" 2>/dev/null | tr '\n' ' ')"
  [ -n "$2" ] && [ -f "$2/implementer.toml" ] && echo "effective codex · $(grep -E '^(model|model_reasoning_effort) = ' "$2/implementer.toml" | tr '\n' ' ')· researcher $(grep -E '^model_reasoning_effort = ' "$2/online-researcher.toml" 2>/dev/null | tr '\n' ' ')"; return 0; }
# Rewrite every generated definition: $1/$2 = Claude model/effort, $3/$4 = Codex model/effort, $5/$6 = researcher efforts (Claude, Codex).
apply_settings() { local cm=$1 lvl=$2 xm=$3 xlvl=$4 rlvl=$5 xrlvl=$6 f e; nc=0; nx=0
  for f in ${cdir:+"$cdir"/*.md}; do [ -f "$f" ] && grep -q "$MARKER" "$f" || continue
    e=$lvl; [ "$(basename "$f" .md)" = online-researcher ] && e=$rlvl
    edit_claude "$f" "$cm" "$e"; nc=$((nc+1)); case "$f" in "$ROOT"/*) refresh_manifest "${f#"$ROOT"/}";; esac; done
  for f in ${xdir:+"$xdir"/*.toml}; do [ -f "$f" ] && grep -q "$MARKER" "$f" || continue
    e=$xlvl; [ "$(basename "$f" .toml)" = online-researcher ] && e=$xrlvl
    edit_codex "$f" "$xm" "$e"; nx=$((nx+1)); refresh_manifest "${f#"$ROOT"/}"; done; }
refresh_manifest() { local r=$1 h; [ -f "$H/installed.tsv" ] && grep -q "	$r\$" "$H/installed.tsv" || return 0   # keep the rewritten file "owned and unmodified"
  h=$(hash_of "$ROOT/$r"); awk -F'\t' -v OFS='\t' -v p="$r" -v h="$h" '$2==p{$1=h}1' "$H/installed.tsv" > "$H/installed.tsv.tmp" && mv "$H/installed.tsv.tmp" "$H/installed.tsv"; }

cmd=${1:-status}
case "$cmd" in
  on)
    ensure_layout || exit 1
    date '+%Y-%m-%d %H:%M' > "$H/state/active"
    echo "mini-harness on · root $ROOT · protocol $H/harness.md · style $(style_path)";;
  off)
    rm -f "$H/state/active"; echo "mini-harness off · root $ROOT";;
  status|doctor)
    fail=0; ok() { echo "ok    $*"; }; warn() { echo "warn  $*"; }; bad() { echo "FAIL  $*"; fail=1; }
    echo "root      $ROOT"
    if [ -f "$H/state/active" ]; then echo "active    yes · since $(head -n1 "$H/state/active")"; else echo "active    no"; fi
    if [ -f "$H/harness.md" ]; then ok "protocol $H/harness.md"; else bad "no $H/harness.md — run: on (plugin) or install.sh (standalone)"; fi
    if [ -s "$H/repo_info/codebase_overview.md" ]; then ok "repo_info initialized (codebase_overview.md non-empty)"; else warn "repo_info not initialized — run: init"; fi
    cur=$(wiki_cursor); echo "traj      $(traj_count) trajectories · $(unconsolidated) unconsolidated (wiki cursor: ${cur:-none})"
    ca=$(ls "$ROOT/.claude/agents" 2>/dev/null | grep -c '\.md$' || true); cx=$(ls "$ROOT/.codex/agents" 2>/dev/null | grep -c '\.toml$' || true)
    echo "workers   .claude/agents: $ca · .codex/agents: $cx (0 = expect the plugin's agents on Claude Code; Codex needs install.sh)"
    cdef="$ROOT/.claude/agents"; [ -f "$cdef/implementer.md" ] || cdef="${PACK:+$PACK/agents}"   # plugin install: the plugin's own agents/
    if [ -n "$cdef" ] && [ -f "$cdef/implementer.md" ]; then echo "effective claude · $(grep -E '^(model|effort):' "$cdef/implementer.md" | tr '\n' ' ')· researcher $(grep -E '^effort:' "$cdef/online-researcher.md" 2>/dev/null | tr '\n' ' ')($cdef; change with: effort; read at session start)"; fi
    if [ -f "$ROOT/.codex/agents/implementer.toml" ]; then echo "effective codex · $(grep -E '^(model|model_reasoning_effort) = ' "$ROOT/.codex/agents/implementer.toml" | tr '\n' ' ')· researcher $(grep -E '^model_reasoning_effort = ' "$ROOT/.codex/agents/online-researcher.toml" 2>/dev/null | tr '\n' ' ')(.codex/agents)"; fi
    [ "$cmd" = status ] && exit 0
    for f in $PROTO_FILES; do [ -f "$H/$f" ] || bad "missing $H/$f"; done
    [ -f "$H/hooks/route.sh" ] && { [ -x "$H/hooks/route.sh" ] && ok "standalone route hook executable" || bad "$H/hooks/route.sh is not executable"; }
    if [ -f "$ROOT/.claude/settings.json" ] && grep -q 'route.sh' "$ROOT/.claude/settings.json"; then
      grep -q '\\"${CLAUDE_PROJECT_DIR}/.harness/hooks/route.sh\\"' "$ROOT/.claude/settings.json" && ok "Claude hook path is quoted" || bad "Claude hook path unquoted — re-run install.sh (F3)"
    else warn "no standalone Claude hook in .claude/settings.json (fine for a plugin install)"; fi
    if [ -f "$ROOT/.codex/hooks.json" ] && grep -q 'route.sh' "$ROOT/.codex/hooks.json"; then
      grep -q 'dirname' "$ROOT/.codex/hooks.json" && ok "Codex hook resolves the root itself (trust it once with /hooks)" || bad "Codex hook uses a cwd-relative path — re-run install.sh (F3)"
    else warn "no standalone Codex hook in .codex/hooks.json (fine for a plugin install)"; fi
    if [ -f "$ROOT/AGENTS.md" ] && grep -q 'mini-harness:begin' "$ROOT/AGENTS.md"; then ok "AGENTS.md carries the block"; else warn "no AGENTS.md block (plugin install: the hook reminder covers routing)"; fi
    if [ -f "$H/installed.tsv" ]; then
      while IFS=$'\t' read -r h p; do
        [ "$h" = link ] && { [ -L "$ROOT/$p" ] || warn "owned link missing: $p"; continue; }
        [ -f "$ROOT/$p" ] || { warn "owned file missing: $p"; continue; }
        [ "$(hash_of "$ROOT/$p")" = "$h" ] || warn "owned file modified locally (install.sh will keep it): $p"
      done < "$H/installed.tsv"
      ok "ownership manifest checked ($(wc -l < "$H/installed.tsv" | tr -d ' ') entries)"
    else warn "no ownership manifest ($H/installed.tsv)"; fi
    [ -f "$H/state/active" ] && [ ! -f "$H/harness.md" ] && bad "active marker without protocol files"
    exit $fail;;
  effort)
    # effort <low|medium|high|xhigh|max|inherit|reset|save|restore> [researcher=<level>] [claude-model=<id|inherit>] [codex-model=<id|inherit>] [model=<id|inherit>]
    # The one effort/model control that works the same on both platforms: both read a worker's effort from its
    # definition (the Claude Code Agent tool takes model aliases only and has no effort parameter; a Codex agent
    # file's settings win over a spawn request). Rewrites only generated definitions; `reset` = shipped defaults.
    # `save` snapshots the current settings to state/effort_saved (kept if one exists); `restore` puts that snapshot
    # back and removes it — a temporary change (init's per-run dials) returns to what the user had, not the shipped defaults.
    lvl=${2:-}; [ -n "$lvl" ] || { echo "usage: mh.sh effort <low|medium|high|xhigh|max|inherit|reset|save|restore> [researcher=<level>] [claude-model=<id|inherit>] [codex-model=<id|inherit>]" >&2; exit 2; }
    shift 2; rlvl=""; cm=""; xm=""; SAVED="$H/state/effort_saved"
    case "$lvl" in save|restore) [ $# -eq 0 ] || { echo "mh.sh effort $lvl takes no arguments" >&2; exit 2; };; esac
    worker_dirs || exit 1
    if [ "$lvl" = save ]; then
      if [ -f "$SAVED" ]; then echo "mini-harness effort · snapshot kept ($SAVED, $(sed -n 's/^saved=//p' "$SAVED")) — restore it before saving another"; exit 0; fi
      mkdir -p "$H/state"
      { echo "saved=$(date '+%Y-%m-%d %H:%M')"
        [ -n "$cdir" ] && [ -f "$cdir/implementer.md" ] && { echo "claude_model=$(claude_val "$cdir/implementer.md" model)"; echo "claude_effort=$(claude_val "$cdir/implementer.md" effort)"; echo "claude_researcher=$(claude_val "$cdir/online-researcher.md" effort)"; }
        [ -n "$xdir" ] && [ -f "$xdir/implementer.toml" ] && { echo "codex_model=$(codex_val "$xdir/implementer.toml" model)"; echo "codex_effort=$(codex_val "$xdir/implementer.toml" model_reasoning_effort)"; echo "codex_researcher=$(codex_val "$xdir/online-researcher.toml" model_reasoning_effort)"; }
      } > "$SAVED"
      echo "mini-harness effort · saved current settings to $SAVED (restore with: effort restore)"; print_effective "$cdir" "$xdir"; exit 0
    fi
    if [ "$lvl" = restore ]; then
      [ -f "$SAVED" ] || { echo "mini-harness effort · no snapshot ($SAVED) — definitions unchanged"; print_effective "$cdir" "$xdir"; exit 0; }
      sv() { sed -n "s/^$1=//p" "$SAVED" | head -n1; }
      when=$(sv saved)
      apply_settings "$(sv claude_model)" "$(sv claude_effort)" "$(sv codex_model)" "$(sv codex_effort)" "$(sv claude_researcher)" "$(sv codex_researcher)"
      rm -f "$SAVED"
      echo "mini-harness effort · restored the settings saved $when · rewrote $nc Claude Code definition(s)${cdir:+ in $cdir} · $nx Codex definition(s)${xdir:+ in $xdir}"
      print_effective "$cdir" "$xdir"; echo "note: a running session may not reload definitions — check each worker's launch metadata and record requested vs effective"; exit 0
    fi
    [ "$lvl" = reset ] && { lvl=low; rlvl=medium; cm=inherit; xm=inherit; }
    for a in "$@"; do case "$a" in
      researcher=*) rlvl=${a#*=};; claude-model=*) cm=${a#*=};; codex-model=*) xm=${a#*=};; model=*) cm=${a#*=}; xm=${a#*=};;
      *) echo "mh.sh effort: unknown argument '$a'" >&2; exit 2;; esac; done
    for l in "$lvl" "$rlvl"; do case "$l" in ""|low|medium|high|xhigh|max|inherit) ;; *) echo "mh.sh effort: unknown level '$l' (low|medium|high|xhigh|max|inherit|reset|save|restore)" >&2; exit 2;; esac; done
    case "$cm" in gpt-*) echo "mh.sh effort: '$cm' is a Codex model — use codex-model=" >&2; exit 2;; *[!A-Za-z0-9._:/-]*) echo "mh.sh effort: bad model id '$cm'" >&2; exit 2;; esac
    case "$xm" in claude-*|opus|sonnet|haiku|fable) echo "mh.sh effort: '$xm' is a Claude model — use claude-model=" >&2; exit 2;; *[!A-Za-z0-9._:/-]*) echo "mh.sh effort: bad model id '$xm'" >&2; exit 2;; esac
    apply_settings "$cm" "$lvl" "$xm" "$lvl" "$rlvl" "$rlvl"
    echo "mini-harness effort · rewrote $nc Claude Code definition(s)${cdir:+ in $cdir} · $nx Codex definition(s)${xdir:+ in $xdir}"
    print_effective "$cdir" "$xdir"
    echo "note: a running session may not reload definitions — check each worker's launch metadata and record requested vs effective"
    exit 0;;
  traj)
    task=${2:?usage: mh.sh traj <task>}; mkdir -p "$H/exec_traj"
    for _ in 1 2 3 4 5; do
      f="$H/exec_traj/$(date '+%Y-%m-%d_%H%M%S')_${task}_$(printf '%04x' $((RANDOM % 65536))).md"
      if ( set -C; : > "$f" ) 2>/dev/null; then
        # Write the schema skeleton so the agent fills blanks instead of reading exec_traj.md.
        { printf '<!-- fill from what the run already holds — effect, not narration; keep `unknown` where unresolved; delete this line -->\n'
          if [ -f "$H/exec_traj.md" ]; then sed -n '/^```md$/,/^```$/p' "$H/exec_traj.md" | sed '1d;$d'
          else printf '# <task> · <YYYY-MM-DD HH:MM> · <platform> · <main model>\nrequest:\noutcome:\nnative path:\nmemory consulted:\nsubagents:\nadvisory:\nadvisor decisions (main agent):\nchanged:\nverification:\nuser choices:\nharness effect:\n- helped:\n- hurt:\n- neutral:\nfriction:\n'; fi
        } | sed "1,2s/^# <task> · <YYYY-MM-DD HH:MM>/# $task · $(date '+%Y-%m-%d %H:%M')/" > "$f"
        printf '%s\n' "$f"; exit 0
      fi
    done; echo "mini-harness: could not create a unique trajectory file" >&2; exit 1;;
  *) echo "usage: mh.sh on | off | status | doctor | traj <task> | effort <level|reset|save|restore> [researcher=<level>] [claude-model=<id>] [codex-model=<id>]" >&2; exit 2;;
esac
